const { siteUrl } = require("./next-sitemap.blog-sources");

/** One ISO timestamp per Node process - used as lastmod for all URLs in a sitemap run. */
let sitemapBuildLastmod = null;

function getSitemapBuildLastmod() {
  if (!sitemapBuildLastmod) {
    sitemapBuildLastmod = new Date().toISOString();
  }
  return sitemapBuildLastmod;
}

/** Sitemap index entries written after sub-sitemaps are generated. */
const SITEMAP_INDEX_FILES = [
  "sitemap-0.xml",
  "page-sitemap.xml",
  "post-sitemap.xml",
  "images-sitemap.xml",
];

/** Paths that must never appear in any sitemap file. */
const EXCLUDED_SITEMAP_PATHS = new Set([
  "/best-content-marketing-agency-delhi-ncr",
  "/career2",
  "/category/digital-marketing-agency",
  "/discussion-forum",
  "/services/content-marketing/content-marketing",
  "/services/print-advertising2",
  "/services/print-advertising2/a",
  "/services/real-estate-walkthrough",
  "/services/Real-Estate-Walkthrough",
  "/tags/accessibility-to-a-wide-range",
  "/tags/ad-agency-in-north-india",
  "/tags/ads-agency",
  "/tags/ads-agency-list",
  "/tags/advertise-agency-in-noda-out-of-house-advertising",
  "/tags/advertise-on-all-india-radio",
  "/tags/advertise-printing",
  "/tags/advertisement-in-hindustan-times",
  "/tags/advertisements",
  "/tags/advertising-ads-agency",
  "/tags/advertising-agency",
  "/tags/advertising-agency-delhi-ncr",
  "/tags/advertising-agency-list",
  "/tags/advertising-companies-in-noida",
  "/tags/advertising-company",
  "/tags/advertising-for-festivals-india",
  "/tags/advertising-in-india",
  "/tags/advertising-printing-services",
  "/tags/advertising-services-in-dainik-jagran",
  "/tags/advertising-strategies",
  "/tags/affordable-classified-ads",
  "/tags/affordable-print-ads-india",
  "/tags/affordable-web-design-delhi-ncr",
  "/tags/affordable-web-design-services-greater-noida",
  "/tags/ai-in-digital-marketing",
  "/tags/air-commercial-rates",
  "/tags/air-fm-radio-ad-agencies",
  "/tags/air-radio-advertising-agencies",
  "/tags/akshay-kumar-levels-up",
  "/tags/akshay-kumar-s-brand-value",
  "/tags/all-india-radio-ad-rates",
  "/tags/all-india-radio-advertising-companies",
  "/tags/all-india-radio-marketing",
  "/tags/amar-ujala-classified-ad-rates",
  "/tags/amar-ujala-newspaper-ad-cost",
  "/tags/amar-ujala-rate-card",
  "/tags/amul",
  "/tags/artist-management-agency",
  "/tags/artist-management-agency-list",
  "/tags/artist-management-agency-near-me",
  "/tags/artist-management-companies",
  "/tags/b2b-digital-marketing-companies-delhi",
  "/tags/benefits-of-digital-marketing",
  "/tags/best-ad-agency-in-delhi-ncr",
  "/tags/best-ad-agency-in-noida",
  "/tags/best-ad-agency-in-north-india",
  "/tags/best-agencies-for-digital-content",
  "/tags/best-content-marketing-agencies",
  "/tags/best-content-marketing-agency-india",
  "/tags/best-creative-advertising-agency-delhi",
  "/tags/best-creative-agency",
  "/tags/best-digital-marketing-agency-in-greater-noida-sector",
  "/tags/best-digital-marketing-services-for-doctors",
  "/tags/best-email-marketing-companies-in-delhi-ncr",
  "/tags/best-google-ads-agencies-in-delhi-ncr",
  "/tags/best-google-my-business-optimization-agency-in-noida",
  "/tags/best-graphic-design-agency-in-noida",
  "/tags/best-hindi-newspapers",
  "/tags/best-hindi-newspapers-for-upsc",
  "/tags/best-online-marketing-agencies-india",
  "/tags/best-ppc-company-in-delhi-ncr",
  "/tags/best-pr-agencies-in-delhi-ncr",
  "/tags/best-print-advertising-agency-in-delhi-ncr-noida",
  "/tags/best-print-advertising-agency-in-north-india",
  "/tags/best-radio-advertising-agency",
  "/tags/best-radio-advertising-delhi-ncr",
  "/tags/best-real-estate-digital-marketing-agency-in-delhi-ncr-2025",
  "/tags/best-real-estate-digital-marketing-agency-noida",
  "/tags/best-seo-company-in-gurgaon",
  "/tags/best-seo-services-in-noida",
  "/tags/best-slot-for-radio-ads",
  "/tags/best-social-media-marketing-services-in-india",
  "/tags/best-time-for-radio-ads",
  "/tags/best-web-design-company-in-noida",
  "/tags/big-fm-advertisement-pricing",
  "/tags/big-fm-advertising-packages",
  "/tags/big-fm-radio-ad-rates",
  "/tags/big-fm-radio-ads-chennai",
  "/tags/big-fm-radio-commercial-rates",
  "/tags/billboard-cost-mumbai",
  "/tags/book-radio-mirchi-ad",
  "/tags/brand-activation-festivals",
  "/tags/brand-awareness",
  "/tags/brand-awareness-through-digital-ads",
  "/tags/brand-influencer-campaigns",
  "/tags/brand-popularity",
  "/tags/brand-promotion-delhi-ncr",
  "/tags/branding-agencies-in-india",
  "/tags/branding-agencies-in-noida",
  "/tags/branding-agency-in-noida",
  "/tags/branding-agency-noida",
  "/tags/branding-companies-delhi",
  "/tags/branding-strategy",
  "/tags/branding-tips",
  "/tags/brands-strategy",
  "/tags/bulk-email-services-delhi",
  "/tags/business-standard-ad-pricing",
  "/tags/campaign-running-on-red-fm",
  "/tags/celebrity-endorsement-agency-in-delhi",
  "/tags/celebrity-endorsement-agency-in-gurgaon",
  "/tags/celebrity-endorsements-agency",
  "/tags/celebrity-influencer-marketing",
  "/tags/celebrity-marketing-agency",
  "/tags/classified-ad-placement",
  "/tags/classified-ads-rates-rs-3150-sq-cm",
  "/tags/community-provides-brands",
  "/tags/compelling-visual-identity",
  "/tags/content-marketing-agencies-in-the-world",
  "/tags/content-marketing-india",
  "/tags/content-marketing-noida",
  "/tags/content-marketing-services-list",
  "/tags/cost-effective-marketing",
  "/tags/cost-effective-newspaper-ads",
  "/tags/cost-of-front-page-ad-in-times-of-india",
  "/tags/creative-ad-agency-in-greater-noida",
  "/tags/creative-agency",
  "/tags/creative-agency-in-delhi",
  "/tags/creative-agency-in-noida",
  "/tags/creative-branding-solutions",
  "/tags/creative-design-solutions",
  "/tags/custom-newspaper-ad-solutions-for-businesses",
  "/tags/d2c-digital-marketing",
  "/tags/dainik-bhaskar-ad-rates",
  "/tags/dainik-jagran",
  "/tags/dainik-jagran-ads-price",
  "/tags/dainik-jagran-advertisement",
  "/tags/dainik-jagran-classified-ad-booking",
  "/tags/dainik-jagran-classified-rates",
  "/tags/deccan-chronicle-ad-rates",
  "/tags/deccan-chronicle-advertising-cost",
  "/tags/deccan-chronicle-classified-ad-rates",
  "/tags/deepikas-fanbase",
  "/tags/delhi-ncr-digital-marketing-experts",
  "/tags/delhi-ncr-seo-solutions",
  "/tags/demonstrating-market",
  "/tags/digital-activation-ideas",
  "/tags/digital-ad-campaign-key-elements",
  "/tags/digital-advertising-agencies-delhi",
  "/tags/digital-creative-agency-delhi-ncr",
  "/tags/digital-hindi-newspapers",
  "/tags/digital-marketing-agencies-in-delhi-ncr",
  "/tags/digital-marketing-agencies-noida",
  "/tags/digital-marketing-agency-gurgaon",
  "/tags/digital-marketing-agency-in-greater-noida",
  "/tags/digital-marketing-agency-in-gurgaon",
  "/tags/digital-marketing-agency-in-north-india",
  "/tags/digital-marketing-agency-noida-2025",
  "/tags/digital-marketing-companies-in-delhi",
  "/tags/digital-marketing-company-in-noida",
  "/tags/digital-marketing-company-in-noida-sector-62",
  "/tags/digital-marketing-for-b2b-brands",
  "/tags/digital-marketing-for-hospitals",
  "/tags/digital-marketing-for-real-estate-in-delhi-ncr",
  "/tags/digital-marketing-for-real-estate-noida",
  "/tags/digital-marketing-for-schools-noida",
  "/tags/digital-marketing-services-in-noida",
  "/tags/digital-print-advertising-india",
  "/tags/direct-activation-advertising-strategy",
  "/tags/disadvantages-of-radio-advertising",
  "/tags/discounted-newspaper-ads",
  "/tags/dj-management-agency-india",
  "/tags/dubai-property-developers",
  "/tags/due-to-their-large-circulation",
  "/tags/e-commerce-website-designing",
  "/tags/education-marketing",
  "/tags/effective-media-advertising",
  "/tags/elevating-your-fashion-brand-promotion",
  "/tags/email-automation-services-noida",
  "/tags/email-marketing",
  "/tags/email-marketing-agencies-noida",
  "/tags/email-marketing-services-delhi",
  "/tags/event-advertising-india",
  "/tags/famous-radio-jockey-in-india",
  "/tags/festival-brand-campaigns",
  "/tags/festive-season-in-india",
  "/tags/fever-fm-ad-booking",
  "/tags/fever-fm-ad-cost",
  "/tags/fever-fm-advertising-rates",
  "/tags/fever-fm-commercial-slots",
  "/tags/fm-radio-ad-rates",
  "/tags/fm-radio-advertising-agency-in-india",
  "/tags/free-seo-tools",
  "/tags/full-page-ads-in-newspaper",
  "/tags/gmb-profile-management-noida",
  "/tags/google-ads",
  "/tags/google-ads-consultants-noida",
  "/tags/google-ads-experts-noida",
  "/tags/google-ads-for-education",
  "/tags/google-ads-for-educational-institutes",
  "/tags/google-advertising-benefits",
  "/tags/government-radio-ad-rates",
  "/tags/government-radio-advertising",
  "/tags/high-reach-classified-ads",
  "/tags/hindi-newspaper-ads-2025",
  "/tags/hindustan-times",
  "/tags/hindustan-times-ad-rate-card",
  "/tags/hindustan-times-ads-rates",
  "/tags/hindustan-times-advertisement-rates",
  "/tags/hindustan-times-advertisements",
  "/tags/hindustan-times-advertising",
  "/tags/hindustan-times-display-ads",
  "/tags/hire-seo-expert-noida",
  "/tags/hoarding-advertising-cost-india",
  "/tags/horizons-isros-historic-lunar",
  "/tags/how-do-i-advertise-on-a-radio-station",
  "/tags/how-much-do-website-designers-charge-in-india",
  "/tags/how-much-does-a-fm-ad-cost",
  "/tags/how-to-advertise-on-red-fm",
  "/tags/ht-ad-booking-online",
  "/tags/improve-local-search-ranking-noida",
  "/tags/increase-sales-with-digital-marketing",
  "/tags/india-s-top-digital-agencies",
  "/tags/indian-brands-that-slowly-faded-away",
  "/tags/indian-market",
  "/tags/indian-radio-frequencies",
  "/tags/influencer-marketing-agency",
  "/tags/influencer-marketing-for-d2c",
  "/tags/influencer-marketing-strategies",
  "/tags/is-print-advertising-effective",
  "/tags/lead-generation-for-educational-institutes",
  "/tags/lead-generation-for-schools-via-ppc",
  "/tags/leading-digital-marketing-firms",
  "/tags/list-of-digital-marketing-agency-in-noida",
  "/tags/local-newspapers-for-classified-ads",
  "/tags/local-seo-for-clinics-in-delhi-ncr",
  "/tags/local-seo-services-noida",
  "/tags/logo-design-agency-delhi",
  "/tags/marketing-agency-delhi",
  "/tags/maximizing-roi",
  "/tags/media-advertising-agency",
  "/tags/media-planning-delhi-ncr",
  "/tags/media-relations-firms-delhi",
  "/tags/medical-marketing-agency-delhi-ncr",
  "/tags/medical-marketing-services-in-india",
  "/tags/mobile-app-advertising-noida",
  "/tags/most-read-hindi-newspapers",
  "/tags/most-trusted-hindi-newspapers",
  "/tags/navbharat-times",
  "/tags/newspaper-ads-today",
  "/tags/newspaper-advertising-cost-india",
  "/tags/nike",
  "/tags/noida-advertising-firms",
  "/tags/noida-graphic-design-studio",
  "/tags/noida-social-media-branding",
]);

/**
 * Path prefixes that must never appear in any sitemap file.
 * Use for dynamic routes (e.g. /services/print-advertising2/[slug]).
 */
const EXCLUDED_SITEMAP_PREFIXES = [
  "/career2",
  "/services/print-advertising2",
  "/discussion-forum",
  "/services/real-estate-walkthrough",
  "/services/Real-Estate-Walkthrough",
];

/** DB / legacy service path → canonical public URL in sitemaps. */
const SERVICE_SITEMAP_PATH_ALIASES = {
  "/services/content-marketing/content-marketing":
    "/services/content-marketing/customized-content-strategy",
};

function normalizeSitemapPath(path) {
  if (typeof path !== "string") return null;
  let normalized = path.trim();
  if (!normalized.startsWith("/")) normalized = `/${normalized}`;
  normalized = normalized.replace(/\/+$/, "") || "/";
  return normalized;
}

function isExcludedSitemapPath(path) {
  const normalized = normalizeSitemapPath(path);
  if (!normalized) return false;
  if (EXCLUDED_SITEMAP_PATHS.has(normalized)) return true;
  for (const prefix of EXCLUDED_SITEMAP_PREFIXES) {
    if (normalized === prefix || normalized.startsWith(`${prefix}/`)) return true;
  }
  return false;
}

function resolveServiceSitemapPath(path) {
  const normalized = normalizeSitemapPath(path);
  if (!normalized) return null;
  if (SERVICE_SITEMAP_PATH_ALIASES[normalized]) {
    return SERVICE_SITEMAP_PATH_ALIASES[normalized];
  }
  if (isExcludedSitemapPath(normalized)) return null;
  return normalized;
}

/** Custom robots.txt policies (also used on production). */
const ROBOTS_POLICIES = [
  { userAgent: "*", disallow: ["/admin/"] },
  { userAgent: "ChatGPT-User", allow: "/" },
  { userAgent: "OAI-SearchBot", allow: "/" },
  { userAgent: "GPTBot", allow: "/" },
  { userAgent: "Google-Extended", allow: "/" },
  { userAgent: "Bingbot", allow: "/" },
];

module.exports = {
  siteUrl,
  SITEMAP_INDEX_FILES,
  ROBOTS_POLICIES,
  EXCLUDED_SITEMAP_PATHS,
  EXCLUDED_SITEMAP_PREFIXES,
  SERVICE_SITEMAP_PATH_ALIASES,
  isExcludedSitemapPath,
  resolveServiceSitemapPath,
  getSitemapBuildLastmod,
};
